[workspace]
resolver = "2"
members = ["hello"]

[workspace.lints.rust]
unsafe_code = "forbid"

[profile.dev]
split-debuginfo = "packed"

[profile.release]
codegen-units = 1
lto = true
panic = "abort"
split-debuginfo = "packed"
strip = true
