service: module-api
frameworkVersion: "3"

provider:
  name: aws
  deploymentMethod: direct
  profile: ${param:profile}
  region: ${param:region}
  runtime: provided.al2023
  memorySize: ${param:memorySize}
  architecture: arm64
  logRetentionInDays: ${param:logRetentionInDays}
  disableRollback: ${param:disableRollback}
  deploymentBucket:
    name: darkord-sls-${sls:stage}-deployment-bucket
    serverSideEncryption: AES256
  apiGateway:
    restApiId: ${param:restApiId}
    restApiRootResourceId: ${param:restApiRootResourceId}
  environment:
    RUST_LOG: ${param:logLevel}
    REGION: ${param:region}
    STAGE: ${sls:stage}
    STAGE_PREFIX: ${param:stagePrefix}
    STAGE_DASH_PREFIX: ${param:stageDashPrefix}
  # For now it is sufficient to not use AWS X-Ray tracing to develop this microservice. Comment out to save cost
  # tracing:
  #   lambda: true

params:
  stage:
    profile: darkord-stage
    region: us-east-1
    memorySize: 128
    logRetentionInDays: 7
    disableRollback: true
    restApiId: ns1o12mqe1
    restApiRootResourceId: webfruxv5f
    logLevel: INFO
    stagePrefix: stage_
    stageDashPrefix: stage-
    authorizerId: pmob2d

  prod:
    profile: darkord
    region: ap-southeast-1
    memorySize: 256
    logRetentionInDays: 7
    disableRollback: false
    restApiId: udz4iyqum3
    restApiRootResourceId: sonnsq55fh
    logLevel: INFO
    stagePrefix: ""
    stageDashPrefix: ""
    authorizerId: "" # todo: Deploy authorizer to production and note the ID

custom:
  deploymentBucket:
    blockPublicAccess: true
  prune:
    automatic: true
    includeLayers: true
    number: 5
  rust:
    cargoLambda:
      docker: false

package:
  individually: true
  patterns:
    - "!**"

functions:
  hello:
    handler: hello
    package:
      patterns:
        - "hello/**"
    iamRoleStatements:
      - Effect: Allow
        Action:
          - ssm:GetParameter
        Resource:
          - arn:aws:ssm:${param:region}:${aws:accountId}:parameter/auth/api/token/session
      - Effect: Allow
        Action:
          - dynamodb:GetItem
          - dynamodb:PutItem
          - dynamodb:UpdateItem
        Resource:
          - arn:aws:dynamodb:${param:region}:${aws:accountId}:table/${param:stagePrefix}auth_attempt
      - Effect: Allow
        Action:
          - dynamodb:PutItem
        Resource:
          - arn:aws:dynamodb:${param:region}:${aws:accountId}:table/${param:stagePrefix}auth_user
    events:
      - http:
          method: POST
          path: /module/hello
          private: true

plugins:
  - serverless-better-credentials # Must be the first one in this list for this to work
  - serverless-rust-plugin
  - serverless-prune-plugin
  - serverless-iam-roles-per-function
  - serverless-deployment-bucket
